[package]
name = "c_to_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust"
crate-type = ["staticlib", "rlib"]

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
once_cell = "1.19.0"

[build-dependencies]
cbindgen = "0.27.0"
cc = "1.1.24"