/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SomeThingCoolS {
    pub t: ::std::os::raw::c_int,
    pub d: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of SomeThingCoolS"][::std::mem::size_of::<SomeThingCoolS>() - 16usize];
    ["Alignment of SomeThingCoolS"][::std::mem::align_of::<SomeThingCoolS>() - 8usize];
    ["Offset of field: SomeThingCoolS::t"][::std::mem::offset_of!(SomeThingCoolS, t) - 0usize];
    ["Offset of field: SomeThingCoolS::d"][::std::mem::offset_of!(SomeThingCoolS, d) - 8usize];
};
pub type SomeThingCool = SomeThingCoolS;
extern "C" {
    pub fn addValuesTogheter(someThingCool: *mut SomeThingCool) -> f64;
}
extern "C" {
    pub fn addTwoValue(x: ::std::os::raw::c_int, y: ::std::os::raw::c_int)
        -> ::std::os::raw::c_int;
}
